@gamersremorse_HostAddress = http://localhost:5221

###

POST {{gamersremorse_HostAddress}}/fingerprints/regenerate
Accept: application/json

###

GET {{gamersremorse_HostAddress}}/wall?sort=sunkCost&order=desc&limit=20
Accept: application/json

###

GET {{gamersremorse_HostAddress}}/wall/similar/2386720
Accept: application/json

###
