// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace gamersremorse.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251216004618_Categories")]
    partial class Categories
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.1");

            modelBuilder.Entity("gamersremorse.Entities.Metadata", b =>
                {
                    b.Property<uint>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("TargetSampleCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalNegative")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalPositive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("TEXT");

                    b.HasKey("AppId");

                    b.ToTable("Metadatas");
                });

            modelBuilder.Entity("gamersremorse.Entities.SteamAppInfo", b =>
                {
                    b.Property<uint>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Flags")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFree")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AppId");

                    b.ToTable("SteamAppInfos");
                });

            modelBuilder.Entity("gamersremorse.Entities.SteamReview", b =>
                {
                    b.Property<long>("AuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<uint>("AppId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("BanterCount")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("ComplaintCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("EditedOn")
                        .HasColumnType("TEXT");

                    b.Property<int>("GamesOwned")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("InsultCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastPlayed")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("PostedOn")
                        .HasColumnType("TEXT");

                    b.Property<byte>("ProfanityCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewLength")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("SlurCount")
                        .HasColumnType("INTEGER");

                    b.Property<TimeSpan>("TimePlayedAtReview")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("TimePlayedInTotal")
                        .HasColumnType("TEXT");

                    b.Property<int>("Verdict")
                        .HasColumnType("INTEGER");

                    b.HasKey("AuthorId", "AppId");

                    b.ToTable("SteamReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
