// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace gamersremorse.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251222043857_InitialPostgres")]
    partial class InitialPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("gamersremorse.Entities.ControversyCache", b =>
                {
                    b.Property<string>("Query")
                        .HasColumnType("text");

                    b.Property<DateTime>("CachedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Overview")
                        .HasColumnType("text");

                    b.HasKey("Query");

                    b.ToTable("ControversyCaches");
                });

            modelBuilder.Entity("gamersremorse.Entities.Fingerprint", b =>
                {
                    b.Property<long>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AppId"));

                    b.Property<TimeSpan>("NegMedian")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("PosMedian")
                        .HasColumnType("interval");

                    b.Property<Vector>("Shape")
                        .IsRequired()
                        .HasColumnType("vector(12000)");

                    b.Property<byte[]>("Snapshot")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<int>("SteamNegative")
                        .HasColumnType("integer");

                    b.Property<int>("SteamPositive")
                        .HasColumnType("integer");

                    b.Property<byte[]>("ThumbnailPng")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AppId");

                    b.ToTable("Fingerprints");
                });

            modelBuilder.Entity("gamersremorse.Entities.Metadata", b =>
                {
                    b.Property<long>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AppId"));

                    b.Property<bool>("IsStreaming")
                        .HasColumnType("boolean");

                    b.Property<bool>("NegativeExhausted")
                        .HasColumnType("boolean");

                    b.Property<bool>("PositiveExhausted")
                        .HasColumnType("boolean");

                    b.Property<int>("SampledNegative")
                        .HasColumnType("integer");

                    b.Property<int>("SampledPositive")
                        .HasColumnType("integer");

                    b.Property<int>("TargetSampleCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalNegative")
                        .HasColumnType("integer");

                    b.Property<int>("TotalPositive")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AppId");

                    b.ToTable("Metadatas");
                });

            modelBuilder.Entity("gamersremorse.Entities.SteamAppInfo", b =>
                {
                    b.Property<long>("AppId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("AppId"));

                    b.Property<int>("Flags")
                        .HasColumnType("integer");

                    b.Property<string>("HeaderImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsFree")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AppId");

                    b.ToTable("SteamAppInfos");
                });

            modelBuilder.Entity("gamersremorse.Entities.SteamReview", b =>
                {
                    b.Property<long>("AuthorId")
                        .HasColumnType("bigint");

                    b.Property<long>("AppId")
                        .HasColumnType("bigint");

                    b.Property<byte>("BanterCount")
                        .HasColumnType("smallint");

                    b.Property<byte>("ComplaintCount")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("EditedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("GamesOwned")
                        .HasColumnType("integer");

                    b.Property<byte>("InsultCount")
                        .HasColumnType("smallint");

                    b.Property<DateTimeOffset>("LastPlayed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PostedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte>("ProfanityCount")
                        .HasColumnType("smallint");

                    b.Property<int>("ReviewLength")
                        .HasColumnType("integer");

                    b.Property<byte>("SlurCount")
                        .HasColumnType("smallint");

                    b.Property<TimeSpan>("TimePlayedAtReview")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("TimePlayedInTotal")
                        .HasColumnType("interval");

                    b.Property<int>("Verdict")
                        .HasColumnType("integer");

                    b.HasKey("AuthorId", "AppId");

                    b.ToTable("SteamReviews");
                });
#pragma warning restore 612, 618
        }
    }
}
